ROUTER_ADDRESS=%ROUTER_ADDRESS%

PROXY_IP=%PROXY_IP%
PROXY_PORT=%PROXY_PORT%
PROXY_TRANSP_PORT=%PROXY_TRANSP_PORT%

LAN_NETWORK=%LAN_NETWORK%
LAN_NETMASK_EXPAND=%LAN_NETMASK_EXPAND%
LAN_NETMASK=%LAN_NETMASK%

ROUTER_IP=%ROUTER_IP%
VM_NAME=%VM_NAME%